### ISSUE TITLE
Launcher fails to start on Windows XP

### ISSUE THREAD

**Issue by brotalnia** [pohmelie/pypod-launcher#3]
I hear a message box sound when starting the launcher, but nothing happens. The process appears in task manager for a second and then disappears. If i start it in compatibility mode with Windows 2000, then I see this error message.

![Untitled](https://user-images.githubusercontent.com/6519171/77180395-85e0cc80-6ad2-11ea-86d6-09a6330872ba.jpg)

**Comment by pohmelie** [comment]
What version are you trying to launch?

**Comment by brotalnia** [comment]
I downloaded the latest launcher from here -> https://github.com/pohmelie/pypod-launcher/releases/tag/0.3.2

Also this is a bit off topic, but I want to mention for anyone else who may want to try playing this mod on XP, that the game itself will not run XP even if you install the mod on another PC first and then copy everything to the XP machine to bypass the launcher. You will get an error about a missing function in kernel32.dll, and I managed to fix this by making a patch for D2PoDClient.dll, which can be downloaded [here](https://github.com/brotalnia/EU4_WinXP_fix/releases/tag/pod1).

**Comment by pohmelie** [comment]
@brotalnia unfortunatelly have no winxp machine or virtual os to test your bug. I test this on win10 and under linux wine. But I definitely played in diablo II LOD under win xp on my old PC nearly 2010 and have no problems. More to say, I remember win7 users had problems and ask for help in game server forum I've played at.

**Comment by pohmelie** [comment]
And, also, I'm absolutely sure I run d2 under winxp with virtualbox.

**Comment by brotalnia** [comment]
Clean Diablo 2 can run on XP without issues. Its the Path of Diablo mod that does not work on XP. It comes with a DLL file that is linked against a newer version of kernel32.dll and uses functions which do not exist in XP.

**Comment by pohmelie** [comment]
Ah, got it. Thanks for information. You can check directory, which is mentioned in popup window (but don't close the popup) for any files. Launcher binaries should unpack to temporary directory. But it looks like something goes wrong.

**Comment by pohmelie** [comment]
Check out new release [v0.4.0](https://github.com/pohmelie/pypod-launcher/releases/tag/0.4.0), maybe it will work for you.

**Comment by GreenDude120** [comment]
PoD mod requires vista and above yes. no real way to avoid that sadly

**Comment by pohmelie** [comment]
Ok, so I'm closing this.
