### ISSUE TITLE
Widescreen support

### ISSUE THREAD

**Issue by aliankarali** [pohmelie/pypod-launcher#4]
Path of diablo launcher now has widescreen support. There is a checkbox that reads widescreen which adds `-widescreen` launch option. Could you please add it?

**Comment by pohmelie** [comment]
Amazing feature! Thank you for information. Released in [v0.4.0](https://github.com/pohmelie/pypod-launcher/releases/tag/0.4.0).

**Comment by aliankarali** [comment]
wow thanks for the quick release 🙌
