### ISSUE TITLE
Missing launch flags

### ISSUE THREAD

**Issue by GreenDude120** [pohmelie/pypod-launcher#5]
https://greendu.de/i/vBT.png

D2 Vid Test forces the game to use whatever is saved in the registry by d2vidtest app. so this one might not be useful to linux.
DDraw is very important and is the default way to play now as it supports smooth upscaling shaders.
Widescreen needs to be on by default now that it is stable because many players look for 1068x600 in the video options but it wont show up without this enabled.
-cpufix prevents the game from running unlimited fps and locks the fps at a lower amount to reduce %cpu usage.
-sndbkg means the game sounds continues even when alt tabbed

we made the video modes radial options instead of checkboxes because only one can truly be enabled at once and players may not not the priority order the game uses.

please consider removing the option to skip updates. the reason we want every1 using pod launcher and same files is because ppl come to use with issues and they dont immediately tell us things like "im not running latest update" or "im on linux" until later. its a huge waste of time for our team. if we catch a bug and patch it, we want to know all our users have the fix.

optional: we added sound notifications for loot filter so u may want to add that support in ur jinja generator.

thanks

**Comment by pohmelie** [comment]
Thank you for such amount of useful information, I will make changes soon (even if only I use this project 🥲 ).

> D2 Vid Test forces the game to use whatever is saved in the registry by d2vidtest app. so this one might not be useful to linux.

Wine is look alike full windows, so it of course have registry in runtime and you can run d2vidtest, so do glide.exe to change glider settings.

> DDraw is very important and is the default way to play now as it supports smooth upscaling shaders.

Am I right, that ddraw mode is only for fullscreen?

> please consider removing the option to skip updates

Do you mean «check for updates on start» checkbox?

> we added sound notifications for loot filter so u may want to add that support in ur jinja generator

I know only about color notifications. Where can I read about this?

**Comment by GreenDude120** [comment]
Am I right, that ddraw mode is only for fullscreen?

No you can config it in ddraw.ini. it can do anything like glide but also shaders

Do you mean «check for updates on start» checkbox?

yes id like it removed

**Comment by pohmelie** [comment]
Fixed in new release, thank you for information.
